import { db } from "@/lib/firebase";
import { collection, query, where, getDocs, limit } from "firebase/firestore";

interface PageProps {
    params: Promise<{
        slotId: string;
    }>;
}

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function AgentPromptPage({ params }: PageProps) {
    const { slotId } = await params;
    const slot = parseInt(slotId);

    if (isNaN(slot)) {
        return <div>Invalid Slot Number</div>;
    }

    let promptContent = "Waiting for agent assignment...";
    let agentName = "Unknown Agent";

    try {
        if (!db || (Object.keys(db).length === 0 && db.constructor === Object)) {
            // In a page, we can return a friendly error UI
            return <div>Database configuration missing on server.</div>;
        }

        // Find the subworkspace assigned to this slot
        const q = query(
            collection(db, "subworkspaces"),
            where("retell_slot", "==", slot),
            limit(1)
        );

        const snapshot = await getDocs(q);

        if (!snapshot.empty) {
            const data = snapshot.docs[0].data();
            agentName = data.name || "Agent";

            // Priority: active_prompt > combined prompts
            if (data.active_prompt) {
                promptContent = data.active_prompt;
            } else {
                const corePrompt = data.prompt_core_text || "";
                const editablePrompt = data.prompt_editable_text || "";
                promptContent = `${corePrompt}\n\n${editablePrompt}`;
            }
        }

    } catch (error) {
        console.error("Error fetching agent prompt:", error);
        return <div>Error loading prompt. Please check permissions.</div>;
    }

    return (
        <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '800px', margin: '40px auto', padding: '20px' }}>
            <head>
                <title>{`Agent Prompt - ${agentName}`}</title>
                <meta name="description" content={`System prompt configuration for agent slot ${slot}`} />
                <meta name="robots" content="noindex, nofollow" />
                {/* Wait, Retell needs to read it. But we don't want Google to index it? 
                   If we set noindex, Retell might respect it and show 0!
                   We MUST set index, follow or at least not noindex.
                */}
                <meta name="robots" content="index, follow" />
            </head>
            <nav style={{ marginBottom: '20px', fontSize: '14px', color: '#666' }}>
                <a href="/" style={{ color: '#0066cc', textDecoration: 'none' }}>Home</a> &gt; <span>Slot {slot}</span>
            </nav>
            <main>
                <h1 style={{ fontSize: '24px', marginBottom: '20px' }}>Prompt: {agentName}</h1>
                <div style={{ padding: '20px', backgroundColor: '#f9f9f9', border: '1px solid #eee', borderRadius: '8px' }}>
                    <h2 style={{ fontSize: '14px', color: '#666', textTransform: 'uppercase', marginBottom: '10px' }}>System Instructions</h2>
                    <article style={{ whiteSpace: 'pre-wrap', lineHeight: '1.6', fontSize: '16px', color: '#333' }}>
                        {promptContent}
                    </article>
                </div>
            </main>
            <footer style={{ marginTop: '40px', fontSize: '12px', color: '#888', borderTop: '1px solid #eee', paddingTop: '20px' }}>
                <p>Generated by VoiceCRM for Retell AI Integration.</p>
                <p><a href={`/agent-view/${slot}`} style={{ color: '#888' }}>Permalink</a></p>
            </footer>
        </div>
    );
}
