import { db } from "@/lib/firebase";
import { collection, query, where, getDocs, limit } from "firebase/firestore";

interface PageProps {
    params: Promise<{
        slotId: string;
    }>;
}

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function AgentPromptPage({ params }: PageProps) {
    const { slotId } = await params;
    const slot = parseInt(slotId);

    if (isNaN(slot)) {
        return <div>Invalid Slot Number</div>;
    }

    let promptContent = "Waiting for agent assignment...";
    let agentName = "Unknown Agent";

    try {
        if (!db || (Object.keys(db).length === 0 && db.constructor === Object)) {
            // In a page, we can return a friendly error UI
            return <div>Database configuration missing on server.</div>;
        }

        // Find the subworkspace assigned to this slot
        const q = query(
            collection(db, "subworkspaces"),
            where("retell_slot", "==", slot),
            limit(1)
        );

        const snapshot = await getDocs(q);

        if (!snapshot.empty) {
            const data = snapshot.docs[0].data();
            agentName = data.name || "Agent";

            // Priority: active_prompt > combined prompts
            if (data.active_prompt) {
                promptContent = data.active_prompt;
            } else {
                const corePrompt = data.prompt_core_text || "";
                const editablePrompt = data.prompt_editable_text || "";
                promptContent = `${corePrompt}\n\n${editablePrompt}`;
            }
        }

    } catch (error) {
        console.error("Error fetching agent prompt:", error);
        return <div>Error loading prompt. Please check permissions.</div>;
    }

    return (
        <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '800px', margin: '40px auto', padding: '20px' }}>
            <h1 style={{ fontSize: '24px', marginBottom: '20px' }}>Prompt for {agentName} (Slot {slot})</h1>
            <hr style={{ marginBottom: '20px', borderColor: '#eee' }} />

            <article style={{ whiteSpace: 'pre-wrap', lineHeight: '1.6', fontSize: '16px' }}>
                {promptContent}
            </article>

            <footer style={{ marginTop: '40px', fontSize: '12px', color: '#888' }}>
                Generated by VoiceCRM for Retell Integration
            </footer>
        </div>
    );
}
